// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const lib = import('/util/vendor/measure-lossy.js?v=a8c6e3bd')
const kHz = hz => (hz / 1000).toFixed(1) + '<small>kHz</small>'

export default async function process(a, o, ui) {
  const lossy = (await lib).default
  const fs = a.sampleRate, nyq = fs / 2
  const r = lossy(a.channelData, { fs })
  const pct = Math.round(r.confidence * 100)
  const known = isFinite(r.cutoff)

  // long-term average spectrum, drawn in the worker: no DOM here, so grid lines and the curve only
  const W = 1200, H = 360, canvas = new OffscreenCanvas(W, H), ctx = canvas.getContext('2d')
  ctx.fillStyle = '#0d1014'; ctx.fillRect(0, 0, W, H)
  const fmin = 20
  const fx = f => W * Math.log(f / fmin) / Math.log(nyq / fmin)
  ctx.strokeStyle = 'rgba(237,235,228,.15)'; ctx.lineWidth = 1
  for (const f of [50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000]) { if (f <= fmin || f >= nyq) continue; const x = fx(f); ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke() }
  for (let i = 1; i < 4; i++) { const y = H * i / 4; ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke() }
  const { freqs, db } = r.spectrum
  let maxDb = -Infinity
  for (let i = 0; i < freqs.length; i++) if (freqs[i] >= fmin && db[i] > maxDb) maxDb = db[i]
  const minDb = maxDb - 90
  const fy = d => H * (1 - (Math.max(minDb, Math.min(maxDb, d)) - minDb) / (maxDb - minDb))
  ctx.strokeStyle = '#00a4b8'; ctx.lineWidth = 2; ctx.beginPath()
  let started = false
  for (let i = 0; i < freqs.length; i++) {
    if (freqs[i] < fmin) continue
    const x = fx(Math.min(freqs[i], nyq)), y = fy(db[i])
    if (started) ctx.lineTo(x, y); else { ctx.moveTo(x, y); started = true }
  }
  ctx.stroke()
  if (known && r.cutoff > fmin && r.cutoff < nyq * 0.995) {
    const x = fx(r.cutoff)
    ctx.strokeStyle = 'rgba(237,235,228,.5)'; ctx.setLineDash([5, 4]); ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); ctx.setLineDash([])
  }

  const report = [
    { k: 'Verdict', cls: r.lossy ? 'warn' : 'ok', v: (r.lossy ? 'Lossy source detected' : 'No lossy signature found') + '<small>' + (r.lossy ? r.source + ' guess, ' : '') + pct + '% confidence</small>' },
    { k: 'Cutoff frequency', v: known ? kHz(r.cutoff) : 'unknown<small>file too short</small>',
      note: !known ? 'Not enough audio to estimate a spectral cutoff reliably.' :
        'Content reaches ' + (r.cutoff / 1000).toFixed(1) + ' kHz; this ' + (fs / 1000) + ' kHz file could carry content up to ' + (nyq / 1000).toFixed(1) + ' kHz, its Nyquist frequency. ' +
        (nyq - r.cutoff < 500 ? 'No real gap between the two: this looks like full bandwidth.' : 'The gap between them is what a codec lowpass filter leaves behind.') },
    { k: 'Edge sharpness', v: (Math.round(r.evidence.cutoffSharpness) || 0) + '<small>dB/oct</small>',
      note: r.evidence.cutoffSharpness > 60 ? 'Steeper than 60 dB/octave: the signature of an encoder brick-wall lowpass filter, not a microphone or tape roll-off.' : 'Gentle slope: consistent with a natural roll-off (microphone, tape, room) rather than a codec filter.' },
    { k: 'Spectral holes', v: r.evidence.holes.toFixed(1) + '<small>/s</small>',
      note: 'Persistent gaps in the 4-16 kHz band where an encoder ran out of bits for that frame. More than a couple per second is the low-bitrate MP3 swiss-cheese pattern.' },
    { k: 'Upsampled', v: r.evidence.upsampled ? 'Yes' : 'No',
      note: r.evidence.upsampled ? 'The cutoff sits at a clean fraction of the sample rate: this looks like a lower-rate source padded back up, not a bitrate-driven codec filter.' : 'The cutoff does not line up with a simple fraction of the sample rate.' },
    { k: 'What this means', cls: 'list wide',
      v: 'This test loses power above roughly 128-160 kbps: a well-tuned high-bitrate MP3 or AAC can show no lowpass at all and read as lossless. It can also misfire the other way on naturally band-limited audio, an old tape dub, a narrow-band microphone, heavy de-essing, plain speech, which can look exactly like a lossy cutoff. Read the cutoff, edge sharpness and spectral holes together; do not trust the verdict alone.' },
  ]
  return { report, viz: { width: W, height: H, data: ctx.getImageData(0, 0, W, H).data } }
}
