// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const lib = load('https://esm.sh/@audio/denoise-dewow@0.1.0')
const LOW_CONF = 'Few stable partials — try the reference mode or the pitch mode.'

export default async function process(a, o, ui) {
  const { default: dewow, analyze } = await lib
  const fs = a.sampleRate
  const mode = o.mode || 'partial', refFreq = +o.refFreq || 50
  const wow = !!o.wow, flutter = !!o.flutter
  const n = a.channelData[0].length, mono = new Float32Array(n)
  for (const ch of a.channelData) for (let i = 0; i < n; i++) mono[i] += ch[i] / a.channelData.length
  const curveOpts = { fs, mode, refFreq, wow, flutter }

  ui.status('Measuring speed drift…')
  await new Promise(r => setTimeout(r, 20))
  const before = analyze(mono, curveOpts)

  ui.status('Correcting speed…')
  await new Promise(r => setTimeout(r, 20))
  const channelData = dewow(a.channelData, curveOpts)

  ui.status('Checking the result…')
  await new Promise(r => setTimeout(r, 20))
  const outN = channelData[0].length, outMono = new Float32Array(outN)
  for (const ch of channelData) for (let i = 0; i < outN; i++) outMono[i] += ch[i] / channelData.length
  const after = analyze(outMono, curveOpts)

  let lo = Infinity, hi = -Infinity
  for (const s of before.speed) { if (s < lo) lo = s; if (s > hi) hi = s }

  const dur = n / fs, W = 1200, H = 200
  const canvas = new OffscreenCanvas(W, H), ctx = canvas.getContext('2d')
  ctx.fillStyle = '#0d1014'; ctx.fillRect(0, 0, W, H)
  const range = 3, yOf = dev => H / 2 - Math.max(-range, Math.min(range, dev)) * (H / 2 / range)
  ctx.strokeStyle = 'rgba(237,235,228,.3)'; ctx.lineWidth = 1
  ctx.beginPath(); ctx.moveTo(0, yOf(0)); ctx.lineTo(W, yOf(0)); ctx.stroke()
  const plot = (times, curve, color) => {
    ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.beginPath()
    for (let i = 0; i < curve.length; i++) {
      const x = dur > 0 ? Math.min(W, times[i] / dur * W) : 0, y = yOf((curve[i] - 1) * 100)
      i ? ctx.lineTo(x, y) : ctx.moveTo(x, y)
    }
    ctx.stroke()
  }
  plot(before.times, before.speed, 'rgba(237,235,228,.5)')
  plot(after.times, after.speed, '#00a4b8')
  ctx.fillStyle = 'rgba(237,235,228,.8)'; ctx.font = '600 11px Manrope, sans-serif'
  ctx.fillText('+3%', 6, 13); ctx.fillText('0%', 6, H / 2 + 4); ctx.fillText('-3%', 6, H - 6)

  const pct = x => x.toFixed(2)
  return {
    audio: { channelData, sampleRate: fs }, suffix: '-dewow',
    viz: { width: W, height: H, data: ctx.getImageData(0, 0, W, H).data },
    report: [
      { k: 'Wow', v: pct(before.wowPeak) + ' → ' + pct(after.wowPeak) + '<small>% peak</small>', cls: after.wowPeak < before.wowPeak ? 'ok' : '', note: 'Peak deviation from nominal speed, unweighted (not the IEC 60386 figure). Slow drift, below about 6 Hz.' },
      { k: 'Flutter', v: pct(before.flutterPeak) + ' → ' + pct(after.flutterPeak) + '<small>% peak</small>', cls: after.flutterPeak < before.flutterPeak ? 'ok' : '', note: 'Peak deviation, unweighted. Faster wobble; this analysis only sees it up to about 40 Hz.' },
      { k: 'Confidence', v: (before.confidence * 100).toFixed(0) + '<small>%</small>', cls: before.confidence < 0.5 ? 'warn' : '', note: before.confidence < 0.5 ? LOW_CONF : 'Fraction of the recording with a usable speed reading.' },
      { k: 'Speed range', v: (lo * 100).toFixed(1) + '% – ' + (hi * 100).toFixed(1) + '<small>% of nominal</small>', note: 'The transport speed found in the source, before correction — 100% is nominal.' },
    ],
  }
}
