// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const mirLib = load('https://esm.sh/@audio/mir@1.1.3')
const beatLib = load('https://esm.sh/@audio/beat@2.1.3')
const midiLib = load('https://esm.sh/@audio/midi@1.0.2')
const musicxmlLib = import('/util/vendor/musicxml.js?v=86644131')
const renderLib = import('/util/vendor/midi-render.js?v=46a1da90')
const noteLib = load('https://esm.sh/@audio/note@1.0.2')

const MAJOR = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B']
const MINOR = ['Cm', 'C#m', 'Dm', 'Ebm', 'Em', 'Fm', 'F#m', 'Gm', 'G#m', 'Am', 'Bbm', 'Bm']
const esc = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const keyLabel = k => { const minor = k.slice(-1) === 'm', root = minor ? k.slice(0, -1) : k; return root.split('#').join('♯').split('b').join('♭') + ' ' + (minor ? 'minor' : 'major') }

export default async function process(a, o, ui) {
  const fs = a.sampleRate
  const n = a.channelData[0].length, mono = new Float32Array(n)
  for (const ch of a.channelData) for (let i = 0; i < n; i++) mono[i] += ch[i] / a.channelData.length

  let bpm, tempoAuto = !o.tempo, tempoConfidence = null
  if (!tempoAuto) bpm = +o.tempo
  else {
ui.status('Tracking the beat…'); await new Promise(r => setTimeout(r, 20))
const { detect } = await beatLib
const b = detect(mono.subarray(0, Math.min(n, fs * 90)), { fs })
bpm = Math.round(b.bpm); tempoConfidence = b.confidence
  }

  ui.status('Listening for notes…'); await new Promise(r => setTimeout(r, 20))
  const { transcribe, chroma, key } = await mirLib
  const minDuration = (+o.minNote || 80) / 1000
  const notes = transcribe(mono, { fs, minDuration })
  if (!notes.length) throw Error('No notes detected. Try a shorter minimum note length, or a file with a single clear melody line.')

  let keyStr, keyAuto = !o.key || o.key === 'auto', keyConfidence = null
  if (keyAuto) {
const span = Math.min(n, fs * 120), frames = []
for (let i = 0; i + 4096 <= span; i += 4096) frames.push(chroma(mono.subarray(i, i + 4096), { fs }))
const k = key(frames)
keyStr = (k.mode === 'minor' ? MINOR : MAJOR)[k.tonic]
keyConfidence = k.confidence
  } else keyStr = o.key

  const quantize = +o.quantize || 0
  const { write } = await midiLib
  const smf = write(notes, { bpm })
  const { default: writeMusicxml, toAbc } = await musicxmlLib
  const xml = writeMusicxml(notes, { bpm, key: keyStr, quantize, title: 'Transcription' })
  const abc = toAbc(notes, { bpm, key: keyStr, quantize })

  ui.status('Rendering the transcription…'); await new Promise(r => setTimeout(r, 20))
  const render = (await renderLib).default
  const rendered = render(smf, { fs })

  const { name } = await noteLib
  const midis = notes.map(nn => nn.midi)
  const lo = Math.min(...midis), hi = Math.max(...midis)

  const lines = abc.split('\n')
  let kIdx = 0
  for (let i = 0; i < lines.length; i++) if (lines[i].indexOf('K:') === 0) { kIdx = i; break }
  const body = lines.slice(kIdx + 1).join(' ')
  const closeAt = body.lastIndexOf('|]')
  const trimmedBody = (closeAt >= 0 ? body.slice(0, closeAt) : body).trim()
  const barTokens = trimmedBody.split('|').map(s => s.trim()).filter(Boolean)
  const bars = barTokens.slice(0, 8).join(' | ') + (barTokens.length > 8 ? ' …' : '')

  return {
report: [
  { k: 'Notes found', v: String(notes.length) },
  { k: 'Tempo used', v: bpm + '<small>BPM</small>', note: tempoAuto ? (tempoConfidence < 0.4 ? 'Detected automatically, low confidence — set it manually if the notes look mistimed.' : 'Detected automatically from the beat.') : 'Set manually.' },
  { k: 'Key', v: keyLabel(keyStr) + (keyAuto ? '<small>' + Math.round(keyConfidence * 100) + '% sure</small>' : ''), note: keyAuto ? 'Detected from chroma frames over the first two minutes; used to spell the notation.' : 'Set manually.' },
  { k: 'Pitch range', v: name(lo) + '–' + name(hi) },
  { k: 'First bars', cls: 'list wide', v: '<code>' + esc(bars) + '</code>', note: 'ABC notation. Polyphonic recognition is approximate: best on monophonic melodies, piano and clean guitar. For a full mix, use an ML transcription tool instead.' },
],
audio: { channelData: rendered.channelData, sampleRate: rendered.sampleRate },
files: [
  { name: 'transcription.mid', data: smf, mime: 'audio/midi', label: 'Save MIDI' },
  { name: 'transcription.musicxml', data: xml, mime: 'application/vnd.recordare.musicxml+xml', label: 'Save MusicXML' },
  { name: 'transcription.abc', data: abc, mime: 'text/plain', label: 'Save ABC' },
],
  }
}
