// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const stft = import('https://esm.sh/@audio/stft@1.0.5')
const spectral = import('https://esm.sh/@audio/spectral@1.2.3')

export default async function process(a, o) {
  const { stftAnalyse } = await stft, { centroid } = await spectral
  const fs = a.sampleRate, n = a.channelData[0].length, mono = new Float32Array(n)
  for (const ch of a.channelData) for (let i = 0; i < n; i++) mono[i] += ch[i] / a.channels
  const frameSize = +o.frame || 2048, W = 1200, H = 400
  const hopSize = Math.max(frameSize / 8, Math.ceil(n / W))
  const frames = [], peaks = new Float64Array(frameSize / 2 + 1); let cent = 0, count = 0
  stftAnalyse(mono, mag => { frames.push(Float32Array.from(mag)); for (let k = 0; k < mag.length; k++) peaks[k] = Math.max(peaks[k], mag[k]); try { const c = centroid(mag, { fs }); if (c > 0) { cent += c; count++ } } catch {} }, { fs, frameSize, hopSize })
  const canvas = new OffscreenCanvas(W, H)
  const ctx = canvas.getContext('2d'), img = ctx.createImageData(W, H)
  const bins = frameSize / 2 + 1, nyq = fs / 2, fmin = 20, log = o.scale !== 'linear'
  let maxDb = -Infinity; for (const f of frames) for (let k = 1; k < bins; k++) { const v = f[k]; if (v > 0) { const d = 20 * Math.log10(v); if (d > maxDb) maxDb = d } }
  for (let x = 0; x < W; x++) {
const f = frames[Math.min(frames.length - 1, Math.floor(x / W * frames.length))]
for (let y = 0; y < H; y++) {
  const fr = log ? fmin * Math.pow(nyq / fmin, 1 - y / H) : nyq * (1 - y / H)
  const k = Math.min(bins - 1, Math.round(fr / nyq * (bins - 1)))
  const db = f[k] > 0 ? 20 * Math.log10(f[k]) - maxDb : -120
  const t = Math.max(0, Math.min(1, (db + 90) / 90)) // 90 dB range
  const i = (y * W + x) * 4
  img.data[i] = 13 + 240 * Math.pow(t, 1.6); img.data[i + 1] = 16 + 150 * Math.pow(t, 2.2); img.data[i + 2] = 20 + 90 * t; img.data[i + 3] = 255
}
  }
  ctx.putImageData(img, 0, 0)
  ctx.fillStyle = 'rgba(237,235,228,.85)'; ctx.font = '600 12px Manrope, sans-serif'
  for (const fr of (log ? [50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000] : [2000, 5000, 10000, 15000, 20000])) { if (fr >= nyq) continue; const y = log ? H * (1 - Math.log(fr / fmin) / Math.log(nyq / fmin)) : H * (1 - fr / nyq); ctx.fillRect(0, y, W, 1); ctx.fillText(fr >= 1000 ? fr / 1000 + ' kHz' : fr + ' Hz', 6, y - 3) }
  let pk = 1; for (let k = 2; k < bins; k++) if (peaks[k] > peaks[pk]) pk = k
  let hi = bins - 1; while (hi > 1 && 20 * Math.log10(peaks[hi] / peaks[pk] || 1e-9) < -60) hi--
  return { viz: { width: W, height: H, data: ctx.getImageData(0, 0, W, H).data }, report: [
{ k: 'Strongest frequency', v: fmtHz(pk / (bins - 1) * nyq) },
{ k: 'Content extends to', v: fmtHz(hi / (bins - 1) * nyq), note: 'Highest frequency within 60 dB of the peak. A hard wall below 16 kHz usually means a lossy source; content to 20 kHz means a lossless or high-bitrate one.' },
...(count ? [{ k: 'Spectral centroid', v: fmtHz(cent / count), note: 'Average brightness: where the energy balances.' }] : []),
{ k: 'Resolution', v: (fs / frameSize).toFixed(1) + '<small>Hz</small> / ' + (hopSize / fs * 1000).toFixed(0) + '<small>ms</small>' },
  ] }
  function fmtHz(f) { return f >= 1000 ? (f / 1000).toFixed(2) + '<small>kHz</small>' : f.toFixed(0) + '<small>Hz</small>' }
}
