// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const lib = load('https://esm.sh/@audio/vocals@1.0.4')

export default async function process(a, o) {
  if (a.channels < 2) throw Error('This needs a stereo file: center-channel extraction has nothing to work with in mono.')
  const { remove, isolate } = await lib
  const [L, R] = [a.channelData[0].slice(), a.channelData[1].slice()]
  const out = (o.mode === 'isolate' ? isolate : remove)([L, R])
  return { audio: { channelData: out, sampleRate: a.sampleRate }, suffix: o.mode === 'isolate' ? '-vocals' : '-karaoke',
report: [{ k: o.mode === 'isolate' ? 'Kept' : 'Removed', v: 'center channel', note: 'Mid/side separation: whatever is panned dead center (usually the lead vocal, often also bass and kick) is ' + (o.mode === 'isolate' ? 'kept' : 'cancelled') + '. Wide reverb and doubled vocals remain. This is the classic phase-cancellation method, not AI source separation.' }] }
}
