// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const renderLib = import('/util/vendor/midi-render.js?v=46a1da90')
const parseLib = load('https://esm.sh/@audio/midi-parse@1.0.2')

export default async function process(a, o, ui) {
  const parse = (await parseLib).default
  let parsed
  try { parsed = parse(a.bytes) } catch (e) { throw Error('Could not read this MIDI file: ' + e.message) }
  const fs = +o.rate || 44100
  const channels = +o.channels === 1 ? 1 : 2
  const tempoScale = (+o.tempo || 100) / 100
  const transpose = +o.semitones || 0
  ui.status('Rendering ' + parsed.notes.length + ' notes with the synth atoms…')
  await new Promise(r => setTimeout(r, 20))
  const { default: render, GM } = await renderLib
  const t0 = performance.now()
  const out = render(parsed, { fs, channels, tempoScale, transpose })
  const ms = performance.now() - t0

  // resolve the GM program in effect at each note — the same rule @audio/midi-render applies internally
  const progEvents = new Map()
  for (const track of parsed.tracks) for (const e of track) {
    if (e.type !== 'program' || e.channel == null) continue
    let evs = progEvents.get(e.channel); if (!evs) progEvents.set(e.channel, evs = []); evs.push(e)
  }
  for (const evs of progEvents.values()) evs.sort((x, y) => x.time - y.time)
  const lastAtOrBefore = (events, t) => { let r; for (const e of events) { if (e.time <= t) r = e; else break } return r }
  const names = new Set(); let drums = false
  for (const n of parsed.notes) {
    if (n.channel === 9) { drums = true; continue }
    const evs = progEvents.get(n.channel) || []
    const p = evs.length ? (lastAtOrBefore(evs, n.time)?.program ?? 0) : 0
    names.add(GM.programs[p]?.name || ('Program ' + p))
  }
  if (drums) names.add('Percussion (GM drum kit)')

  const duration = out.channelData[0].length / fs
  return {
    audio: { channelData: out.channelData, sampleRate: fs }, suffix: '',
    report: [
      { k: 'Notes', v: String(parsed.notes.length) },
      { k: 'Tracks', v: String(parsed.tracks.length) },
      { k: 'Instruments used', cls: 'list wide', v: [...names].join(' · '), note: 'Every voice is synthesized (FM, Karplus–Strong, modal resonators) from its General MIDI program number — no soundfont, no samples.' },
      { k: 'Length', v: fmtTime(duration) },
      { k: 'Render time', v: Math.round(ms) + '<small>ms</small>' },
    ]
  }
}
