// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const lib = load('https://esm.sh/@audio/denoise@0.3.7')
const WHY = { wiener: 'steady broadband noise floor', omlsa: 'noise under speech, speech-presence tracking', specsub: 'stationary noise, spectral subtraction', dehum: 'mains hum and harmonics', declick: 'impulsive clicks', decrackle: 'dense crackle', declip: 'clipped peaks', dewind: 'low-frequency wind rumble', deplosive: 'plosive pops', deesser: 'sibilance', dereverb: 'room reverberation', gate: 'noise between phrases' }

export default async function process(a, o, ui) {
  const m = await lib, fs = a.sampleRate
  let plan = null
  const channelData = []
  for (let c = 0; c < a.channelData.length; c++) {
ui.status((o.method ? 'Applying ' + o.method : 'Classifying and cleaning') + (a.channelData.length > 1 ? ' · channel ' + (c + 1) : '') + '…')
await new Promise(r => setTimeout(r, 20))
const src = a.channelData[c].slice()
if (o.method) channelData.push(m[o.method](src, { fs }))
else { const r = m.denoise(src, { fs, returnPlan: true }); plan ??= r.plan; channelData.push(r.out) }
  }
  const method = o.method || plan?.method || 'wiener'
  const scores = plan?.scores ? Object.entries(plan.scores).filter(([k, v]) => typeof v === 'number' && k !== 'humFreq').map(([k, v]) => k + ' ' + v.toFixed(1)).join(' · ') : ''
  return {
report: [{ k: o.method ? 'Method' : 'Method chosen by the classifier', v: method, note: (WHY[method] || '') + (scores ? '. Detector scores: ' + scores : '') }],
audio: { channelData, sampleRate: fs }, suffix: '-' + method
  }
}
