// Generated by scripts/util-pages.mjs — do not edit; run `npm run build`.
export const DECODE = 'https://esm.sh/@audio/decode@3.15.0'
export const ENCODE = 'https://esm.sh/@audio/encode@1.6.5'
export const META = 'https://esm.sh/@audio/decode@3.14.1/meta'
export const TYPE = 'https://esm.sh/audio-type@2.7.0'
export const MIC = 'https://esm.sh/@audio/mic@1.1.2'
