// Generated by scripts/util-pages.mjs — do not edit; run `npm run build`.
export const DECODE = '/util/vendor/decode/index.js?v=9937d5e2'
export const ENCODE = 'https://esm.sh/@audio/encode@1.6.5'
export const META = 'https://esm.sh/@audio/decode@3.14.1/meta'
export const TYPE = '/util/vendor/audio-type.js?v=1c1c37c0'
export const MIC = 'https://esm.sh/@audio/mic@1.1.2'
