// audiojs utilities — shared shell: file in → decode → process → report / encode → save.
// Pages call tool({ process }) for file tools; live tools use mic() and the helpers.

// package URLs: generated by scripts/util-pages.mjs — a vendored bundle while a package is unpublished, esm.sh once it is
import { DECODE, ENCODE, META, TYPE, MIC } from './libs.js'
const WORKER = new URL('./worker.js', import.meta.url)

export const FORMATS = {
  mp3: { label: 'MP3 · 256 kbps', ext: 'mp3', mime: 'audio/mpeg', opts: { bitrate: 256 } },
  wav: { label: 'WAV · 16-bit', ext: 'wav', mime: 'audio/wav', opts: { bitDepth: 16 } },
  flac: { label: 'FLAC · lossless', ext: 'flac', mime: 'audio/flac', opts: {} },
  ogg: { label: 'OGG Vorbis', ext: 'ogg', mime: 'audio/ogg', opts: { quality: 6 } },
  opus: { label: 'Opus', ext: 'opus', mime: 'audio/ogg; codecs=opus', opts: { bitrate: 128 } },
  aac: { label: 'AAC', ext: 'aac', mime: 'audio/aac', opts: { bitrate: 192 } },
  webm: { label: 'WebM · Opus', ext: 'webm', mime: 'audio/webm; codecs=opus', opts: { bitrate: 128 } },
  aiff: { label: 'AIFF · 16-bit', ext: 'aiff', mime: 'audio/aiff', opts: { bitDepth: 16 } },
  caf: { label: 'CAF · 16-bit', ext: 'caf', mime: 'audio/x-caf', opts: { bitDepth: 16 } },
  qoa: { label: 'QOA', ext: 'qoa', mime: 'audio/qoa', opts: {} },
  // `enc` names the @audio/encode format when it differs from the key (ALAC is the m4a container with another codec)
  m4a: { label: 'M4A · AAC', ext: 'm4a', mime: 'audio/mp4; codecs=mp4a.40.2', opts: { codec: 'aac', bitrate: 192 } },
  alac: { label: 'ALAC · Apple Lossless (M4A)', ext: 'm4a', mime: 'audio/mp4; codecs=alac', enc: 'm4a', opts: { codec: 'alac' } },
  wv: { label: 'WavPack · lossless', ext: 'wv', mime: 'audio/wavpack', opts: {} },
}

let decodeP, encodeP, micP, metaP
export const decodeLib = () => decodeP ??= import(DECODE).then(m => m.default)
export const encodeLib = () => encodeP ??= import(ENCODE).then(m => m.default)
export const micLib = () => micP ??= import(MIC).then(m => m.default)
const metaLib = () => metaP ??= Promise.all([import(META), import(TYPE)]).then(([parsers, type]) => ({ parsers, type: type.default }))

// container tags (title, artist, album, cover art…) — parsed from the source bytes, carried to the encoder
async function readMeta(bytes) {
  try {
    const { parsers, type } = await metaLib()
    const parse = parsers[type(bytes)]
    const meta = parse?.(bytes)?.meta
    if (!meta) return null
    const { raw, ...tags } = meta   // `raw` is the parser's block dump; encoders take the tag keys + pictures
    return Object.keys(tags).some(k => k !== 'pictures' || tags.pictures?.length) ? tags : null
  } catch (e) { console.warn('meta:', e.message); return null }
}

export const $ = id => document.getElementById(id)
export const fmtSize = n => n < 1e6 ? (n / 1e3).toFixed(0) + ' KB' : n < 1e9 ? (n / 1e6).toFixed(1) + ' MB' : (n / 1e9).toFixed(2) + ' GB'
export const fmtTime = s => { s = Math.round(s); const m = Math.floor(s / 60); return (m >= 60 ? Math.floor(m / 60) + ':' + String(m % 60).padStart(2, '0') : m) + ':' + String(s % 60).padStart(2, '0') }
export const chLabel = n => n === 1 ? 'mono' : n === 2 ? 'stereo' : n === 6 ? '5.1' : n + ' ch'
export const el = (tag, attrs = {}, ...children) => { const e = document.createElement(tag); for (const [k, v] of Object.entries(attrs)) k === 'class' ? e.className = v : k === 'html' ? e.innerHTML = v : e.setAttribute(k, v); e.append(...children); return e }

// ── decode: @audio/decode (JS/WASM demux + codecs) → browser decoder → real-time capture ──
export async function decodeFile(file, onProgress) {
  const bytes = new Uint8Array(await file.arrayBuffer())
  const meta = readMeta(bytes)   // tags parse alongside the decode; never rejects
  try {
    const { channelData, sampleRate } = await (await decodeLib())(bytes)
    if (!channelData.length) throw Error('empty')
    return { channelData, sampleRate, meta: await meta }
  } catch (e) { console.warn('@audio/decode:', e.message) }
  try {
    const b = await new OfflineAudioContext(1, 1, 48000).decodeAudioData(bytes.buffer.slice(0))
    return { channelData: Array.from({ length: b.numberOfChannels }, (_, c) => b.getChannelData(c)), sampleRate: b.sampleRate, meta: await meta }
  } catch (e) { console.warn('decodeAudioData:', e.message) }
  return { ...await capture(file, onProgress), meta: await meta }
}

// last resort: play the file silently through the audio graph and record PCM in real time
async function capture(f, onProgress) {
  const RATE = 48000
  const ctx = new AudioContext({ sampleRate: RATE })
  await ctx.resume()
  const src = URL.createObjectURL(f)
  const video = Object.assign(document.createElement('video'), { src, preload: 'auto', crossOrigin: 'anonymous' })
  video.style.display = 'none'; document.body.append(video)
  try {
    await new Promise((res, rej) => { video.onloadedmetadata = res; video.onerror = () => rej(Error('cannot play')) })
    const worklet = URL.createObjectURL(new Blob([`registerProcessor('rec', class extends AudioWorkletProcessor {
      process(inputs) { const i = inputs[0]; if (i.length) this.port.postMessage(i.map(c => c.slice())); return true }
    })`], { type: 'text/javascript' }))
    await ctx.audioWorklet.addModule(worklet)
    const rec = new AudioWorkletNode(ctx, 'rec'), mute = new GainNode(ctx, { gain: 0 })
    const chunks = []; let nch = 0
    rec.port.onmessage = e => { chunks.push(e.data); nch = Math.max(nch, e.data.length) }
    ctx.createMediaElementSource(video).connect(rec).connect(mute).connect(ctx.destination)
    const tick = setInterval(() => onProgress?.(video.currentTime / video.duration || 0), 200)
    await video.play()
    await new Promise((res, rej) => { video.onended = res; video.onerror = () => rej(Error('playback failed')) })
    clearInterval(tick)
    rec.port.onmessage = null
    const len = chunks.reduce((n, c) => n + c[0].length, 0)
    const channelData = Array.from({ length: nch || 1 }, (_, ch) => { const d = new Float32Array(len); let off = 0; for (const c of chunks) { d.set(c[ch] || c[0], off); off += c[0].length } return d })
    return { channelData, sampleRate: RATE }
  } finally { video.remove(); URL.revokeObjectURL(src); ctx.close() }
}

export async function encodeAudio(fmt, audio, opts = {}) {
  const f = FORMATS[fmt], enc = await encodeLib()
  const bytes = await enc[f.enc || fmt](audio.channelData, { sampleRate: audio.sampleRate, ...f.opts, ...(audio.meta && { meta: audio.meta }), ...opts })
  return new Blob([bytes], { type: f.mime })
}

function toCanvas({ width, height, data }) {
  const c = el('canvas'); c.width = width; c.height = height
  c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(data.buffer), width, height), 0, 0)
  return c
}

export const audioBuffer = ({ channelData, sampleRate, meta = null }) => ({ channelData, sampleRate, meta, duration: channelData[0].length / sampleRate, channels: channelData.length })

// ── off-thread processing: cfg.process may be a module URL whose default export is process(audio, opts, ui) ──
function workerRunner(url) {
  const worker = new Worker(WORKER, { type: 'module' })
  let seq = 0, pending = null
  worker.onmessage = e => {
    const { id, type } = e.data
    if (!pending || id !== pending.id) return
    if (type === 'status') pending.ui.status(e.data.msg)
    else if (type === 'progress') pending.ui.progress(e.data.p)
    else if (type === 'done') { const { resolve } = pending; pending = null; resolve(e.data.result) }
    else if (type === 'error') { const { reject } = pending; pending = null; reject(Error(e.data.message)) }
  }
  worker.onerror = e => { if (pending) { const { reject } = pending; pending = null; reject(Error(e.message || 'Worker failed')) } }
  return (audio, opts, ui) => new Promise((resolve, reject) => {
    const id = ++seq
    pending = { id, ui, resolve, reject }
    // structured clone keeps the main-thread copy for re-runs when options change (raw bytes: clone, transfer the clone)
    const { meta, bytes, ...plain } = audio
    if (bytes) plain.bytes = bytes.slice()
    worker.postMessage({ id, url, audio: plain, opts }, plain.bytes ? [plain.bytes.buffer] : [])
  })
}

// ── drop zone: the `drop()` partial wired to one file callback ──
// Click, Enter/Space and the hidden input pick a file; a file dragged or pasted anywhere on the page goes to the
// first visible zone, a file dropped on a zone goes to that zone. hide() once a file is in (the panel takes its
// place), show() on "Another file".
const zones = []
const primary = () => zones.find(z => !z.zone.hidden) || zones[0]   // results showing: a file dropped on the page still replaces the current one
export function dropzone(zone, input, onFile) {
  const pick = f => { if (f) onFile(f) }
  zone.addEventListener('click', () => input.click())
  zone.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); input.click() } })
  input.addEventListener('change', () => { pick(input.files[0]); input.value = '' })
  zone.addEventListener('dragover', () => zone.classList.add('over'))
  zone.addEventListener('dragleave', () => zone.classList.remove('over'))
  zone.addEventListener('drop', e => { e.preventDefault(); e.stopPropagation(); zone.classList.remove('over'); pick(e.dataTransfer.files[0]) })
  if (!zones.length) {
    for (const ev of ['dragenter', 'dragover']) document.addEventListener(ev, e => { e.preventDefault(); primary()?.zone.classList.add('over') })
    for (const ev of ['dragleave', 'drop']) document.addEventListener(ev, e => { e.preventDefault(); primary()?.zone.classList.remove('over') })
    document.addEventListener('drop', e => primary()?.pick(e.dataTransfer.files[0]))
    document.addEventListener('paste', e => primary()?.pick(e.clipboardData?.files[0]))
  }
  const z = { zone, pick, hide: () => { zone.hidden = true }, show: () => { zone.hidden = false; zone.focus() } }
  zones.push(z)
  return z
}

// ── file tool ──
// cfg.process: (audio, opts, ui) → { audio?, report?: [{ k, v, cls?, note? }], viz?: Node | ImageData-like, suffix?, files?: [{ name, data: Uint8Array | string | Blob, mime? }] }
//   or a module URL run in a Worker (default export with the same signature)
// cfg.formats: subset of FORMATS keys · cfg.encodeOpts(fmt, opts) → extra encoder options · cfg.onFormat(fmt) on init and change
// cfg.raw: don't decode the file — process() receives { bytes, name, size } (MIDI, containers, anything that isn't PCM)
// result.files: extra downloads (subtitles, MIDI, scores, remuxed video…) shown next to the audio save button, or alone
export function tool(cfg) {
  const execute = typeof cfg.process === 'string' ? workerRunner(cfg.process) : cfg.process
  const drop = $('drop'), input = $('file'), opts = $('opts')
  const panel = el('section', { class: 'panel', id: 'panel', hidden: '', 'aria-live': 'polite' })
  const name = el('div', { class: 'n' }), meta = el('div', { class: 'm' })
  const reset = el('button', { class: 'btn ghost', type: 'button' }, 'Another file')
  const status = el('div', { class: 'status' }), bar = el('div', { class: 'bar' }, el('i'))
  const progress = el('div', { class: 'row' }, status, bar)
  const report = el('div', { class: 'row report', hidden: '' })
  const viz = el('div', { class: 'row viz', hidden: '' })
  const player = el('audio', { controls: '', preload: 'metadata' })
  const fmt = el('select', {}, ...Object.entries(FORMATS).filter(([k]) => !cfg.formats || cfg.formats.includes(k)).map(([k, f]) => el('option', { value: k }, f.label)))
  const saveLabel = el('span', {}, 'Save')
  const previewNote = el('div', { class: 'note', hidden: '' })
  const save = el('a', { class: 'btn', download: '' }, el('span', { html: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M8 2v8m0 0L4.5 6.5M8 10l3.5-3.5M2.5 13.5h11"/></svg>' }), saveLabel)
  const fmtLabel = el('label', { class: 'fmt' }, 'Format ', fmt)
  const files = el('div', { class: 'row files', hidden: '' })
  const out = el('div', { class: 'row out', hidden: '' }, player, previewNote, fmtLabel, el('span', { class: 'spacer' }), save)
  panel.append(el('div', { class: 'row' }, el('div', { class: 'file' }, name, meta), reset), progress, report, viz, files, out)
  ;(opts || drop).after(panel)
  fmt.value = cfg.defaultFormat || 'mp3'
  cfg.onFormat?.(fmt.value)

  let run = 0, file = null, audio = null, result = null, url = null
  const zone = dropzone(drop, input, load)
  reset.addEventListener('click', () => { run++; release(); panel.hidden = true; zone.show() })
  fmt.addEventListener('change', () => { cfg.onFormat?.(fmt.value); result?.audio && encode() })
  opts?.addEventListener('change', () => audio && process())
  opts?.addEventListener('input', e => { const o = e.target.closest('label')?.querySelector('output'); if (o && e.target.type === 'range') o.value = e.target.value })

  const ui = {
    status(msg, busy = true) { progress.hidden = false; status.textContent = msg; status.classList.remove('err'); bar.hidden = false; bar.classList.toggle('busy', busy) },
    progress(p) { bar.classList.remove('busy'); bar.firstElementChild.style.width = (p * 100).toFixed(1) + '%' },
    error(msg) { progress.hidden = false; status.textContent = msg; status.classList.add('err'); bar.hidden = true },
    opts: () => opts ? Object.fromEntries(new FormData(opts)) : {},
  }
  const release = () => { if (url) URL.revokeObjectURL(url); url = null; if (player.src.startsWith('blob:')) URL.revokeObjectURL(player.src); player.removeAttribute('src'); previewNote.hidden = true; for (const a of files.querySelectorAll('a')) URL.revokeObjectURL(a.href); files.replaceChildren(); files.hidden = true; audio = result = null }
  const yieldUI = () => new Promise(r => setTimeout(r, 30))

  async function load(f) {
    const id = ++run
    release(); file = f
    zone.hide()
    panel.hidden = false; report.hidden = viz.hidden = out.hidden = true
    name.textContent = f.name; meta.textContent = fmtSize(f.size)
    if (cfg.raw) {   // the bytes are the input: no decode, no audio line
      audio = { bytes: new Uint8Array(await f.arrayBuffer()), name: f.name, size: f.size, meta: null }
      if (id !== run) return
      return process(id)
    }
    ui.status('Decoding…')
    try {
      const a = audioBuffer(await decodeFile(f, p => id === run && (status.textContent = 'Capturing playback… ' + (p * 100 | 0) + '%', ui.progress(p))))
      if (id !== run) return
      audio = a
      const tags = [a.meta?.title, a.meta?.artist].filter(Boolean).join(' — ')
      meta.textContent = `${fmtSize(f.size)} · ${fmtTime(a.duration)} · ${chLabel(a.channels)} · ${a.sampleRate / 1000} kHz${tags ? ' · ' + tags : ''}`
      await process(id)
    } catch (e) {
      if (id !== run) return
      console.error(e)
      ui.error(`Can't read this file: no decoder for it here or in your browser. Try a different container.`)
    }
  }

  async function process(id = run) {
    ui.status(cfg.busy || 'Processing…')
    report.hidden = viz.hidden = out.hidden = true
    await yieldUI()
    try {
      result = await execute(audio, ui.opts(), ui)
      if (id !== run) return
      if (result.report) { report.replaceChildren(...result.report.map(r => el('div', { class: /\bwide\b/.test(r.cls || '') ? 'wide' : '' }, el('div', { class: 'k' }, r.k), el('div', { class: 'v' + (r.cls ? ' ' + r.cls : ''), html: r.v }), ...(r.note ? [el('div', { class: 'note' }, r.note)] : [])))); report.hidden = false }
      if (result.viz) { viz.replaceChildren(result.viz instanceof Node ? result.viz : toCanvas(result.viz)); viz.hidden = false }
      if (result.files?.length) {
        files.replaceChildren(...result.files.map(f => {
          const blob = f.data instanceof Blob ? f.data : new Blob([f.data], { type: f.mime || (typeof f.data === 'string' ? 'text/plain' : 'application/octet-stream') })
          const ext = f.name.split('.').pop().toUpperCase()
          return el('a', { class: 'btn', download: f.name, href: URL.createObjectURL(blob) }, el('span', { html: save.firstElementChild.innerHTML }), el('span', {}, `${f.label || 'Save ' + ext} · ${fmtSize(blob.size)}`))
        }))
        files.hidden = false
      }
      if (result.audio) await encode(id)
      else progress.hidden = true
    } catch (e) {
      if (id !== run) return
      console.error(e)
      ui.error(e.message || 'Processing failed')
    }
  }

  async function encode(id = run) {
    const f = fmt.value
    out.hidden = true
    ui.status(f === 'wav' ? 'Writing WAV…' : `Encoding ${f.toUpperCase()}…`)
    try {
      // source tags ride along unless the processor set its own (or `meta: null` to drop them); worker results arrive without them
      const blob = await encodeAudio(f, { meta: audio?.meta, ...result.audio }, cfg.encodeOpts?.(f, ui.opts()) || {})
      if (id !== run) return
      if (url) URL.revokeObjectURL(url)
      url = URL.createObjectURL(blob)
      save.href = url
      // preview: a browser that cannot play the target (Safari with Ogg Opus) gets a WAV copy of the same audio
      if (player.src.startsWith('blob:') && player.src !== url) URL.revokeObjectURL(player.src)
      if (player.canPlayType(FORMATS[f].mime)) { player.src = url; previewNote.hidden = true }
      else { player.src = URL.createObjectURL(await encodeAudio('wav', result.audio)); previewNote.textContent = 'This browser cannot play ' + FORMATS[f].ext.toUpperCase() + ' in the preview; you are hearing a WAV copy of the same audio. The saved file is ' + FORMATS[f].ext.toUpperCase() + '.'; previewNote.hidden = false }
      let base = file.name.replace(/\.[^.]+$/, '') + (result.suffix || '')
      if (!result.suffix && file.name.toLowerCase() === (base + '.' + FORMATS[f].ext).toLowerCase()) base += '-converted'
      save.download = base + '.' + FORMATS[f].ext
      saveLabel.textContent = `Save ${FORMATS[f].ext.toUpperCase()} · ${fmtSize(blob.size)}`
      progress.hidden = true; out.hidden = false
    } catch (e) {
      if (id !== run) return
      console.error(e)
      ui.error(`${f.toUpperCase()} encoding isn't available in this browser. Pick another format.`)
      out.hidden = false
    }
  }
  return { load }
}

// ── live microphone: cb(Float32Array mono chunk, sampleRate) → stop() ──
export async function mic(cb, { sampleRate = 48000 } = {}) {
  // own the context: the browser may not honour the requested rate, and the true rate must reach the caller
  const context = new AudioContext({ sampleRate })
  sampleRate = context.sampleRate
  const read = await (await micLib())({ sampleRate, channels: 1, bitDepth: 32, context })
  let live = true
  // read(cb) is a one-shot pull: re-arm from inside the callback so no chunk is missed
  const loop = (err, pcm) => { if (!live) return; if (!err && pcm) cb(new Float32Array(pcm.buffer, pcm.byteOffset, pcm.byteLength >> 2), sampleRate); if (live) read(loop) }
  read(loop)
  return () => { live = false; read(null); context.close() }
}

export function saveBlob(anchor, blob, filename) {
  if (anchor.href?.startsWith('blob:')) URL.revokeObjectURL(anchor.href)
  anchor.href = URL.createObjectURL(blob)
  anchor.download = filename
}
