// Build the unmodified WORLD reference engine plus our small C ABI wrapper.
// Clone https://github.com/mmorise/World and check out the revision below, then:
// node scripts/prosody-world.mjs /path/to/World
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, join } from 'node:path'
const revision = 'd625e7608ca23a870018f01e7c562ac683d9847f'
const root = process.argv[2] && resolve(process.argv[2])
if (!root || execFileSync('git', ['-C', root, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() !== revision)
  throw Error(`Supply a WORLD checkout at ${revision}.`)
const sources = ['harvest', 'cheaptrick', 'd4c', 'synthesis', 'common', 'fft', 'matlabfunctions']
const output = 'util/prosody/world.wasm.js'
execFileSync('emcc', ['scripts/prosody-world.cpp', ...sources.map(f => join(root, 'src', f + '.cpp')),
  '-I' + join(root, 'src'), '-O3', '-sMODULARIZE', '-sEXPORT_ES6', '-sSINGLE_FILE', '-sSINGLE_FILE_BINARY_ENCODE=0',
  '-sWASM_ASYNC_COMPILATION=0', '-sENVIRONMENT=web,worker', '-sALLOW_MEMORY_GROWTH',
  '-sEXPORTED_FUNCTIONS=_malloc,_free,_world_analyze,_world_render', '-sEXPORTED_RUNTIME_METHODS=HEAPF64', '-o', output], { stdio: 'inherit' })
writeFileSync(output, `// WORLD ${revision}; generated by scripts/prosody-world.mjs. BSD-3-Clause: WORLD-LICENSE.txt\n` + readFileSync(output))
writeFileSync('util/prosody/WORLD-LICENSE.txt', readFileSync(join(root, 'LICENSE.txt')))
