// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const resampleLib = load('https://esm.sh/@audio/resample-polyphase@1.0.2')
const rate = r => r >= 1000 ? (r / 1000) + ' kHz' : r + ' Hz'
const chs = n => n === 1 ? 'mono' : n === 2 ? 'stereo' : n + ' ch'

export default async function process(a, o, ui) {
  let { channelData, sampleRate } = a
  const report = [{ k: 'Source', v: rate(sampleRate) + ' · ' + chs(channelData.length), cls: 'list' }]
  const want = +o.channels || 0
  if (want === 1 && channelData.length > 1) {
    const n = channelData[0].length, mono = new Float32Array(n)
    for (const ch of channelData) for (let i = 0; i < n; i++) mono[i] += ch[i] / channelData.length
    channelData = [mono]
  } else if (want === 2 && channelData.length === 1) channelData = [channelData[0], channelData[0].slice()]
  else if (want === 2 && channelData.length > 2) channelData = channelData.slice(0, 2)
  const to = +o.rate || 0
  if (to && to !== sampleRate) {
    ui.status('Resampling ' + rate(sampleRate) + ' → ' + rate(to) + '…')
    const polyphase = (await resampleLib).default
    channelData = channelData.map(ch => polyphase(ch, { from: sampleRate, to }))
    sampleRate = to
  }
  report.push({ k: 'Output', v: rate(sampleRate) + ' · ' + chs(channelData.length), cls: 'list' })
  return { audio: { channelData, sampleRate }, report }
}
