import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import { readFile } from 'node:fs/promises'
import { resolve, extname, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as pw from 'playwright'
import { encode } from '../../util/prosody/process.js'

const root = fileURLToPath(new URL('../../', import.meta.url)).replace(/\/$/, '')
const types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.wav': 'audio/wav' }
const server = createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost'), path = resolve(root, '.' + url.pathname + (url.pathname.endsWith('/') ? 'index.html' : ''))
  if (!path.startsWith(root + sep)) { res.writeHead(403); res.end(); return }
  try { const bytes = await readFile(path); res.writeHead(200, { 'content-type': types[extname(path)] || 'application/octet-stream' }); res.end(bytes) }
  catch { res.writeHead(404); res.end() }
})
await new Promise(r => server.listen(0, '127.0.0.1', r))
const base = `http://127.0.0.1:${server.address().port}`

try {
  for (const engine of (process.argv.length > 2 ? process.argv.slice(2) : ['chromium', 'firefox', 'webkit'])) {
    const browser = await pw[engine].launch()
    try {
      const page = await browser.newPage({ viewport: { width: 1200, height: 1000 }, reducedMotion: 'reduce' })
      // WASM analysis and rendering run for tens of seconds on a loaded machine.
      page.setDefaultTimeout(120000)
      // WAV + the complete edit/export path must work with all external requests blocked.
      await page.route('**/*', route => [base, 'blob:' + base].some(prefix => route.request().url().startsWith(prefix)) ? route.continue() : route.abort())
      const errors = []; page.on('pageerror', e => errors.push(e.message))
      await page.goto(base + '/util/prosody/')
      assert.equal(await page.locator('#editor').isVisible(), false)
      await page.click('#demo')
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('Ready.'))
      const selected = () => page.locator('#selection-start').getAttribute('aria-valuenow').then(async a => [+a, +(await page.locator('#selection-end').getAttribute('aria-valuenow'))])
      const view = () => page.locator('#curve').evaluate(e => [+e.dataset.viewStart, +e.dataset.viewEnd])
      const select = async (start, end) => page.evaluate(([start, end]) => {
        const a = document.querySelector('#selection-start'), b = document.querySelector('#selection-end')
        const key = (e, key, shiftKey = false) => e.dispatchEvent(new KeyboardEvent('keydown', { key, shiftKey, bubbles: true, cancelable: true }))
        key(a, 'Home'); key(b, 'End')
        for (const [e, value] of [[a, start], [b, end]]) {
          key(e, 'Home')
          const steps = Math.round((value - +e.getAttribute('aria-valuenow')) * 100)
          for (let i = 0; i < Math.floor(steps / 10); i++) key(e, 'ArrowRight', true)
          for (let i = 0; i < steps % 10; i++) key(e, 'ArrowRight')
        }
      }, [start, end])
      const before = await page.locator('.target').getAttribute('d')
      assert.ok(before.length > 300, 'speech sample has a pitch contour')
      const centres = () => page.locator('.note').evaluateAll(notes => notes.map(n => n.dataset.center).filter(Boolean).map(Number))
      assert.ok((await centres()).length >= 20, 'syllables are drawn as notes')
      assert.equal(await page.locator('#scope').textContent(), '· all')
      const slide = (id, value) => page.locator('#' + id).fill(String(value))
      assert.equal(await page.locator('#length, #start, #end, #view-position, #point-hz').count(), 0, 'redundant rows and selection inputs are removed')
      assert.equal(await page.locator('#curve-help').isVisible(), false)
      await page.locator('.plot-help summary').click()
      assert.equal(await page.locator('#curve-help').isVisible(), true)
      await page.locator('.plot-help summary').click()
      assert.equal(await page.locator('#point-info').textContent(), '')
      assert.equal(await page.locator('#zoom-less').isDisabled(), true)
      assert.equal(await page.locator('#view-scroll').getAttribute('aria-disabled'), 'true')
      const initialSelection = await selected()
      await page.click('#zoom-in')
      let [a, b] = await view()
      assert.ok(Math.abs(b - a - initialSelection[1] / 2) < .001)
      assert.equal(await page.locator('#render').isDisabled(), true, 'view changes are not audio edits')
      await page.locator('#view-scroll').evaluate(e => { e.scrollLeft = e.scrollWidth })
      await page.waitForFunction(() => +document.querySelector('#curve').dataset.viewStart > 3)
      await page.locator('#view-scroll').focus(); await page.keyboard.press('Home'); await page.keyboard.press('End')
      ;[a, b] = await view()
      assert.ok(a > 3 && Math.abs(b - initialSelection[1]) < .001)
      assert.deepEqual(await selected(), initialSelection, 'panning preserves selection')
      await page.locator('#curve').focus(); await page.keyboard.press('+')
      ;[a, b] = await view(); assert.ok(Math.abs(b - a - initialSelection[1] / 4) < .001)
      await page.keyboard.press('-'); await page.keyboard.press('0')
      assert.equal(await page.locator('.target').getAttribute('d'), before)
      await page.locator('#curve').dispatchEvent('wheel', { deltaY: -100, ctrlKey: true, clientX: 400, clientY: 500 })
      assert.equal(await page.locator('#zoom-less').isEnabled(), true, 'trackpad pinch zooms the waveform')
      const zoomed = await view()
      await page.locator('#curve').dispatchEvent('wheel', { deltaX: 100, deltaY: 0 })
      assert.ok((await view())[0] > zoomed[0], 'horizontal scroll pans')
      await page.click('#zoom-out')
      assert.equal(await page.locator('.target').getAttribute('d'), before)
      const gesture = (type, scale) => page.locator('#curve').evaluate((el, { type, scale }) => {
        const event = new Event(type, { cancelable: true })
        Object.assign(event, { scale }); el.dispatchEvent(event)
      }, { type, scale })
      await gesture('gesturestart', 1); await gesture('gesturechange', 2); await gesture('gesturechange', 3)
      ;[a, b] = await view()
      assert.ok(Math.abs(b - a - initialSelection[1] / 3) < .001, 'Safari cumulative scales do not compound')
      await gesture('gestureend', 3)
      await gesture('gesturestart', 1); await gesture('gesturechange', .5); await gesture('gestureend', .5)
      ;[a, b] = await view()
      assert.ok(Math.abs(b - a - initialSelection[1] * 2 / 3) < .001, 'successive Safari pinches are independent')
      await page.click('#zoom-out')
      if (engine === 'chromium') {
        await page.locator('#curve').scrollIntoViewIfNeeded()
        const chart = await page.locator('#curve').boundingBox()
        const client = await page.context().newCDPSession(page)
        await client.send('Emulation.setTouchEmulationEnabled', { enabled: true, maxTouchPoints: 2 })
        const touch = (type, points) => client.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([id, x, y]) => ({ id, x, y })) })
        const cy = chart.y + 95, cx = chart.x + chart.width / 2
        await touch('touchStart', [[1, cx - 45, cy]])
        await touch('touchMove', [[1, cx - 55, cy + 10]])
        await touch('touchStart', [[1, cx - 55, cy + 10], [2, cx + 45, cy]])
        await touch('touchMove', [[1, cx - 110, cy + 10], [2, cx + 100, cy]])
        const pinchView = await view()
        assert.ok(pinchView[1] - pinchView[0] < initialSelection[1] * .6, 'two-finger pinch zooms')
        assert.deepEqual(await selected(), initialSelection, 'second finger cancels provisional selection')
        await touch('touchEnd', [[1, cx - 110, cy + 10]])
        await touch('touchMove', [[1, cx - 80, cy + 40]])
        await touch('touchEnd', [])
        assert.deepEqual(await selected(), initialSelection, 'remaining finger cannot start an accidental selection')
        await page.click('#zoom-out')
        assert.equal(await page.locator('.target').getAttribute('d'), before, 'pinch does not edit pitch')
        assert.equal(await page.locator('#undo').isDisabled(), true)
        const curvePoint = await page.locator('.target').evaluate(path => {
          const p = path.getPointAtLength(path.getTotalLength() * .4)
          const q = new DOMPoint(p.x, p.y).matrixTransform(path.getScreenCTM())
          return { x: q.x, y: q.y }
        })
        await touch('touchStart', [[1, curvePoint.x, curvePoint.y]])
        await touch('touchMove', [[1, curvePoint.x, curvePoint.y - 25]])
        assert.notEqual(await page.locator('.target').getAttribute('d'), before, 'touch moves pitch provisionally')
        await touch('touchCancel', [])
        assert.equal(await page.locator('.target').getAttribute('d'), before, 'cancellation restores pitch')
        await touch('touchStart', [[1, curvePoint.x, curvePoint.y]])
        await touch('touchMove', [[1, curvePoint.x, curvePoint.y - 25]])
        await touch('touchStart', [[1, curvePoint.x, curvePoint.y - 25], [2, curvePoint.x + 80, curvePoint.y]])
        assert.equal(await page.locator('.target').getAttribute('d'), before, 'second finger rolls back provisional pitch before zooming')
        await touch('touchEnd', [])
        assert.equal(await page.locator('#undo').isDisabled(), true, 'canceled gestures do not enter undo history')
        await client.send('Emulation.setTouchEmulationEnabled', { enabled: false })
        await client.detach()
      }
      // Sliders act live on the selection (all, here); neutral values are no-ops.
      await slide('smooth', 0); await slide('intonation', 100)
      assert.equal(await page.locator('#render').isDisabled(), true, 'neutral corrections are no-ops')
      await slide('smooth', 60)
      assert.equal(await page.locator('#smooth-value').textContent(), '60 ms')
      assert.notEqual(await page.locator('.target').getAttribute('d'), before, 'smoothing previews live')
      await slide('snap', 100); await slide('straighten', 100)
      assert.ok((await centres()).every(c => Math.abs(c - Math.round(c)) < .01), 'snapped notes sit on semitones')
      await slide('snap', 0)
      assert.ok((await centres()).some(c => Math.abs(c - Math.round(c)) > .05), 'sliders recompute from the curve the correction started on')
      await page.click('#undo')
      assert.equal(await page.locator('.target').getAttribute('d'), before, 'one undo removes the whole correction')
      assert.equal(await page.inputValue('#straighten'), '0', 'undo returns the sliders to neutral')
      await page.locator('#curve').focus(); await page.keyboard.press('ControlOrMeta+A')
      for (let i = 0; i < 18; i++) await page.keyboard.press('Shift+ArrowUp')
      assert.notEqual(await page.locator('.target').getAttribute('d'), before, 'transposition exceeds the former octave cap')
      assert.ok(await page.locator('.note').evaluateAll(notes => notes.every(n => { const b = n.getBBox(); return b.y >= 11 && b.y + b.height <= 217 })), 'pitch axis expands to contain large edits')
      const largeShift = await page.locator('.target').getAttribute('d')
      for (let i = 0; i < 60 && !(await page.locator('#status').textContent()).match(/pitch curve/); i++) await page.keyboard.press('Shift+ArrowUp')
      assert.match(await page.locator('#status').textContent(), /pitch curve/, 'moves stop at the synthesis limit')
      assert.doesNotMatch(await page.locator('.target').getAttribute('d'), /NaN|Infinity/, 'rejected edits leave a valid curve')
      await page.click('#reset')
      assert.equal(await page.locator('.target').getAttribute('d'), before, 'reset restores pitch and axis')
      assert.notEqual(largeShift, before)
      await page.keyboard.press('Escape')
      await page.screenshot({ path: `/tmp/audiojs-prosody-${engine}-desktop.png`, fullPage: true })
      await select(.5, 2)
      await page.locator('#curve').focus(); await page.keyboard.press('ControlOrMeta+A')
      assert.deepEqual(await selected(), initialSelection, 'keyboard selects the whole recording')
      await select(.5, 2)
      const handle = await page.locator('#selection-start').boundingBox()
      await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2)
      await page.mouse.down(); await page.mouse.move(handle.x + handle.width / 2 + 30, handle.y + handle.height / 2, { steps: 4 }); await page.mouse.up()
      assert.ok((await selected())[0] > .5, 'selection boundary drags on the plot')
      assert.equal(await page.locator('.target').getAttribute('d'), before, 'selection does not alter pitch')
      await select(.5, 2)
      await slide('intonation', 50)
      assert.notEqual(await page.locator('.target').getAttribute('d'), before)
      assert.equal(await page.locator('#save').getAttribute('href'), null, 'edits invalidate stale export')
      assert.equal(await page.locator('#edited').getAttribute('src'), null, 'edits invalidate stale preview')
      await page.click('#undo')
      assert.equal(await page.locator('.target').getAttribute('d'), before, 'undo restores original curve')
      await slide('intonation', 150)
      assert.equal(await page.locator('#intonation-value').textContent(), '150%')
      assert.notEqual(await page.locator('.target').getAttribute('d'), before, 'intonation can be amplified')
      await page.click('#undo')
      await page.locator('#curve').focus()
      for (let i = 0; i < 3; i++) await page.keyboard.press('Shift+ArrowUp')
      await page.fill('#duration', '2'); await page.click('#retime')
      await page.click('#render')
      await page.waitForFunction(() => document.querySelector('#render-state').textContent.startsWith('Rendered'))
      const output = await page.evaluate(async () => {
        const bytes = await (await fetch(document.querySelector('#save').href)).arrayBuffer(), d = new DataView(bytes)
        return { rate: d.getUint32(24, true), channels: d.getUint16(22, true), seconds: (bytes.byteLength - 44) / 4 / d.getUint32(24, true), name: document.querySelector('#save').download }
      })
      assert.equal(output.rate, 22050); assert.equal(output.channels, 1); assert.ok(Math.abs(output.seconds - 6.678866) < .001)
      assert.equal(output.name, 'speech-sample-prosody.wav')
      await page.evaluate(async () => { await document.querySelector('#edited').play() })
      await page.waitForFunction(() => document.querySelector('#edited').currentTime > .05)
      await page.evaluate(async () => { await document.querySelector('#original').play() })
      assert.equal(await page.locator('#edited').evaluate(e => e.paused), true, 'A/B never plays both together')
      await page.locator('#original').evaluate(e => e.pause())

      // Notes: the keyboard steps through them and moves them; the pointer drags
      // them onto semitones, Alt frees them, a double-click snaps.
      await page.click('#reset')
      const hz = () => page.locator('#point-info').textContent().then(text => +text.match(/([\d.]+) Hz/)[1])
      await page.locator('#curve').focus(); await page.keyboard.press('Escape'); await page.keyboard.press('ArrowRight'); await page.keyboard.press('ArrowRight')
      assert.equal(await page.locator('#scope').textContent(), '· 1 note')
      assert.match(await page.locator('#point-info').textContent(), /^[A-G]♯?\d .*Hz$/)
      const second = await hz()
      await page.keyboard.press('ArrowUp')
      assert.ok(Math.abs(12 * Math.log2(await hz() / second) - .1) < .01, 'arrow moves the note 10 cents')
      await page.click('#undo')
      await page.locator('#curve').scrollIntoViewIfNeeded()
      const blob = async () => { const box = await page.locator('.note.on').first().boundingBox(); return { x: box.x + box.width / 2, y: box.y + box.height / 2 } }
      let at = await blob()
      await page.mouse.move(at.x, at.y); await page.mouse.down(); await page.mouse.move(at.x, at.y - 30, { steps: 5 }); await page.mouse.up()
      assert.match(await page.locator('#point-info').textContent(), /^[A-G]♯?\d · [\d.]+ Hz · was /, 'drag lands the note on a semitone')
      assert.ok(await hz() > second, 'drag raises the note')
      assert.equal(await page.locator('#scope').textContent(), '· 1 note', 'dragging keeps the note selected')
      await page.click('#undo')
      at = await blob()
      await page.keyboard.down('Alt'); await page.mouse.move(at.x, at.y); await page.mouse.down(); await page.mouse.move(at.x, at.y - 7, { steps: 3 }); await page.mouse.up(); await page.keyboard.up('Alt')
      assert.match(await page.locator('#point-info').textContent(), /¢ · [\d.]+ Hz · was /, 'Alt moves freely')
      at = await blob()
      await page.mouse.dblclick(at.x, at.y)
      assert.match(await page.locator('#point-info').textContent(), /^[A-G]♯?\d · /, 'double-click snaps the note')
      await page.keyboard.press('Escape')
      assert.equal(await page.locator('#scope').textContent(), '· all')
      // A typed duration survives hovering the plot on the way to Apply.
      await page.fill('#duration', '100')
      const note = await page.locator('.note').nth(3).boundingBox()
      await page.mouse.move(note.x + note.width / 2, note.y + note.height / 2)
      assert.match(await page.locator('#point-info').textContent(), /Hz/, 'hovering a note shows it')
      await page.mouse.move(note.x + note.width / 2, note.y - 200)
      assert.equal(await page.inputValue('#duration'), '100')
      await page.click('#retime')
      assert.match(await page.locator('#status').textContent(), /half and twice/)
      await page.locator('#curve').scrollIntoViewIfNeeded()
      const chart = await page.locator('#curve').boundingBox()
      await page.mouse.move(chart.x + 160, chart.y + 240)
      await page.mouse.down(); await page.mouse.move(chart.x + 360, chart.y + 240, { steps: 5 }); await page.mouse.up()
      { const [start, end] = await selected(); assert.ok(end > start + .5, 'background drag selects source time') }
      assert.match(await page.locator('#scope').textContent(), /· \d+ notes/)
      await page.mouse.click(chart.x + chart.width - 60, chart.y + 240)
      assert.equal(await page.locator('#scope').textContent(), '· all', 'a click on empty plot clears the selection')
      await page.click('#reset'); await page.click('#render')
      await page.waitForFunction(() => document.querySelector('#render-state').textContent.startsWith('Rendered'))
      assert.equal(await page.locator('.target').getAttribute('d'), before)

      // Pointer selection and zoom remain usable on small screens.
      for (const viewport of [320, 375, 414, 768, 812].map(width => ({ width, height: 812 }))) {
        await page.setViewportSize(viewport)
        await page.evaluate(() => new Promise(requestAnimationFrame))
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
        assert.deepEqual(await page.locator('#editor').evaluate(panel => {
          const box = panel.getBoundingClientRect()
          return [...panel.querySelectorAll('button')].filter(e => e.getClientRects().length).filter(e => { const r = e.getBoundingClientRect(); return r.left < box.left || r.right > box.right + 1 }).map(e => ({ id: e.id, right: e.getBoundingClientRect().right, panel: box.right }))
        }), [], `controls fit within the panel at ${viewport.width}px without clipping`)
        const info = await page.locator('#point-info').boundingBox(), tools = await page.locator('.plot-tools').boundingBox()
        if (info) assert.ok(info.y + info.height <= tools.y || info.x + info.width <= tools.x, 'overlay readout does not overlap zoom controls')
        await page.locator('.plot-help summary').click()
        const help = await page.locator('#curve-help').boundingBox()
        assert.ok(help.x >= 0 && help.x + help.width <= viewport.width, 'help stays within the viewport')
        await page.keyboard.press('Escape')
      }
      await page.setViewportSize({ width: 375, height: 812 })
      await select(1, 2); await page.click('#zoom')
      assert.match(await page.locator('#curve').textContent(), /1.00 s/)
      assert.equal(await page.locator('#rise').isVisible(), true)
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'pitch sliders fit on mobile')
      await page.screenshot({ path: `/tmp/audiojs-prosody-${engine}-mobile.png`, fullPage: true })
      await page.click('#zoom-out')

      // Change file cancels any outstanding render and clears all editing state.
      await slide('rise', 2)
      assert.equal(await page.locator('#rise-value').textContent(), '+2 st')
      for (const engine of ['waveform', 'vocoder']) {
        await page.selectOption('#engine', engine)
        assert.equal(await page.locator('#render').isEnabled(), true, `${engine}: changing the engine calls for a render`)
        await page.click('#render')
        await page.waitForFunction(() => document.querySelector('#render-state').textContent.startsWith('Rendered'))
      }
      await page.selectOption('#engine', 'auto')
      await page.evaluate(() => { document.querySelector('#render').click(); document.querySelector('#replace').click() })
      assert.equal(await page.locator('#editor').isVisible(), false)
      assert.equal(await page.locator('#save').getAttribute('href'), null)
      await page.click('#demo')
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('Ready.'))
      assert.deepEqual(await view(), [0, initialSelection[1]])
      assert.equal(await page.locator('#view-scroll').getAttribute('aria-disabled'), 'true')
      assert.match(await page.locator('#render-state').textContent(), /no edits/)
      assert.equal(await page.locator('#undo').isEnabled(), false)

      const upload = async (kind, seconds = 1) => {
        const samples = new Float32Array(Math.round(16000 * seconds))
        // Harvest scores harmonics: a voice-like tone, not a pure sinusoid.
        if (kind === 'tone') for (let i = 0; i < samples.length; i++) for (let h = 1; h <= 5; h++) samples[i] += .2 * Math.sin(2 * Math.PI * h * 260 * i / 16000) / h
        const bytes = await encode(samples, 16000)
        await page.setInputFiles('#file', { name: `${kind}.wav`, mimeType: 'audio/wav', buffer: Buffer.from(bytes) })
      }
      await upload('silence', 61)
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('No reliable'))
      assert.deepEqual(await view(), [0, 61])
      await page.click('#reset')
      assert.equal(await page.locator('#render').isDisabled(), true, 'resetting unchanged audio keeps the original export')
      assert.equal(await page.locator('#save').evaluate(async a => (await (await fetch(a.href)).arrayBuffer()).byteLength), 44 + 61 * 16000 * 4)
      await upload('silence')
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('No reliable'))
      assert.equal(await page.locator('.target').getAttribute('d'), '')
      await slide('rise', 2); assert.match(await page.locator('#status').textContent(), /No voiced/)
      assert.equal(await page.inputValue('#rise'), '0', 'a rejected correction returns its slider')
      await page.fill('#duration', '1.5'); await page.click('#retime'); await page.click('#render')
      await page.waitForFunction(() => document.querySelector('#render-state').textContent.startsWith('Rendered'))
      await upload('tone')
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('Ready.'))
      assert.notEqual(await page.locator('.target').getAttribute('d'), before, 'different file has independent analysis')
      await upload('silence', .02)
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('No reliable'))
      await upload('silence', .01)
      await page.waitForFunction(() => document.querySelector('#status').textContent.startsWith('No reliable'))
      assert.equal(await page.locator('#save').evaluate(async a => (await (await fetch(a.href)).arrayBuffer()).byteLength), 44 + 160 * 4)
      await upload('silence', 0)
      await page.waitForFunction(() => document.querySelector('#status').textContent.includes('no decodable audio'))
      assert.equal(await page.locator('#editor').isVisible(), false)
      assert.equal(await page.locator('#drop').isVisible(), true)
      assert.deepEqual(errors, [])
      console.log(`✓ ${engine}: sample, notes, live corrections, snapping, duration, export, A/B, undo/reset, keyboard/pointer, mobile, replacement, silence, short/empty input; no external services`)
    } finally { await browser.close() }
  }
} finally { server.close() }
