// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const asrLib = import('/util/vendor/neural-asr.js?v=f2678409')
const subtitleLib = import('/util/vendor/subtitle.js?v=9404dfcf')

const MODEL_LABEL = { 'onnx-community/whisper-tiny': 'Tiny', 'onnx-community/whisper-base': 'Base', 'onnx-community/whisper-small': 'Small' }
// onnx-community's tiny/base/small exports drop cross-attention outputs word-level timestamps need;
// the older Xenova conversions keep them (see @audio/neural-asr README — Limitations).
const WORD_MODEL = { 'onnx-community/whisper-tiny': 'Xenova/whisper-tiny', 'onnx-community/whisper-base': 'Xenova/whisper-base', 'onnx-community/whisper-small': 'Xenova/whisper-small' }
const LANG_NAME = { en: 'English', es: 'Spanish', fr: 'French', de: 'German', it: 'Italian', pt: 'Portuguese', ru: 'Russian', ja: 'Japanese', zh: 'Chinese', ko: 'Korean', hi: 'Hindi', ar: 'Arabic' }
const escHtml = s => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

export default async function process(a, o, ui) {
  const t0 = performance.now()
  const transcribe = (await asrLib).default
  const subtitle = await subtitleLib
  const wantWords = o.timestamps === 'word'
  const baseModel = o.model || 'onnx-community/whisper-base'
  const model = wantWords ? (WORD_MODEL[baseModel] || baseModel) : baseModel
  const language = o.language || 'en'
  ui.status('Loading the speech model…')
  const result = await transcribe(a, {
    model, language, dtype: 'q4', timestamps: wantWords ? 'word' : 'segment',
    progress(info) {
      if (info.status === 'progress' && info.total) { ui.status('Downloading the speech model' + (info.file ? ' — ' + info.file : '') + '… ' + Math.round(info.progress || 0) + '%'); ui.progress((info.progress || 0) / 100) }
      else if (info.status === 'ready') ui.status('Transcribing…')
      else if (info.status === 'initiate') ui.status('Fetching the speech model from huggingface.co (once; your browser caches it after)…')
    },
  })
  const secs = (performance.now() - t0) / 1000
  const text = result.text.trim()
  const wordCount = result.words && result.words.length ? result.words.length : (text ? text.split(' ').filter(Boolean).length : 0)
  // DTW word-alignment occasionally snaps the last word's end far past the audio (a documented
  // transformers.js limitation, see @audio/neural-asr README); clamp to what was actually decoded.
  const words = result.words && result.words.length ? result.words.map(w => ({ ...w, start: Math.min(w.start, a.duration), end: Math.min(Math.max(w.end, w.start), a.duration) })) : result.words
  const cues = wantWords && words && words.length ? subtitle.fromWords(words) : result.segments.map(s => ({ start: s.start, end: s.end, text: s.text }))
  const srt = subtitle.write(cues, 'srt')
  const vtt = subtitle.write(cues, 'vtt')
  const html = result.segments.length ? result.segments.map(s => escHtml(s.text.trim())).join('<br>') : '(no speech detected)'
  return {
    report: [
      { k: 'Language', v: LANG_NAME[language] || language, note: 'Whisper does not detect language automatically; this used the language picked above. Auto sends English.' },
      { k: 'Duration processed', v: fmtTime(a.duration) },
      { k: 'Words', v: wordCount },
      { k: 'Model', v: (MODEL_LABEL[baseModel] || baseModel) + '<small>' + secs.toFixed(1) + 's</small>', note: wantWords ? 'Word timestamps switched the model to ' + model + ', the export with per-word alignment data.' : 'Time includes the model download on first use; later runs on the same model are much faster.' },
      { k: 'Transcript', cls: 'wide list', v: html },
    ],
    files: [
      { name: 'transcript.txt', data: result.text, mime: 'text/plain', label: 'Save TXT' },
      { name: 'transcript.srt', data: srt, mime: 'text/plain', label: 'Save SRT' },
      { name: 'transcript.vtt', data: vtt, mime: 'text/vtt', label: 'Save VTT' },
    ],
  }
}
