// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
const lib = load('https://esm.sh/@audio/denoise-desilence@0.1.0')

const MODE_NOTE = {
  shorten: (minSilence, maxSilence) => 'Pauses longer than ' + minSilence + 's are shortened to ' + maxSilence + 's, cut from the middle so the onset and offset of each phrase survive.',
  remove: (minSilence, pad) => 'Pauses longer than ' + minSilence + 's are cut down to ' + pad + 's kept on each side.',
  trim: () => 'Only silence at the very start and end is removed; pauses inside the recording are left alone.',
}

// gaps between out.segments (kept spans, input-timeline seconds) are exactly the cut spans —
// reusing the library's own output instead of re-deciding which pauses qualify
function complement(ranges, duration) {
  const out = []
  let pos = 0
  for (const r of ranges) { if (r.start > pos) out.push({ start: pos, end: r.start }); pos = Math.max(pos, r.end) }
  if (pos < duration) out.push({ start: pos, end: duration })
  return out
}

// timeline canvas: speech in accent, cut spans in dark red, kept silence in grey
function makeViz(speech, cuts, duration) {
  const W = 1200, H = 60
  if (!duration || speech.length + cuts.length > 20000) return null
  const canvas = new OffscreenCanvas(W, H), ctx = canvas.getContext('2d')
  ctx.fillStyle = 'rgb(241,239,233)'; ctx.fillRect(0, 0, W, H)
  const hit = (t, ranges) => { for (const r of ranges) if (t >= r.start && t < r.end) return true; return false }
  for (let x = 0; x < W; x++) {
    const t = duration * (x + 0.5) / W
    ctx.fillStyle = hit(t, speech) ? 'rgb(0,164,184)' : hit(t, cuts) ? 'rgb(179,38,30)' : 'rgb(107,111,115)'
    ctx.fillRect(x, 12, 1, H - 24)
  }
  return { width: W, height: H, data: ctx.getImageData(0, 0, W, H).data }
}

export default async function process(a, o, ui) {
  const { default: desilence, segments } = await lib
  const fs = a.sampleRate
  const mode = o.mode || 'shorten'
  const minSilence = +o.minSilence || 0.5
  const maxSilence = +o.maxSilence || 0.25
  const pad = +o.pad || 0.1
  const opts = { fs, mode, minSilence, maxSilence, pad }

  ui.status('Finding pauses…')
  const channels = a.channelData
  const duration = channels[0].length / fs

  const { speech } = segments(channels, { fs })
  const speechSec = speech.reduce((s, x) => s + (x.end - x.start), 0)
  const speechPct = duration > 0 ? speechSec / duration * 100 : 0

  const out = desilence(channels, opts)
  const newDuration = out.data[0].length / fs
  const cuts = complement(out.segments, duration)
  const removedPct = duration > 0 ? out.removed / duration * 100 : 0

  const report = [
    { k: 'Speech found', v: speechPct.toFixed(0) + '<small>%</small>', note: speech.length + ' phrase' + (speech.length === 1 ? '' : 's') + ' detected by voice activity detection, ' + speechSec.toFixed(1) + 's of ' + fmtTime(duration) + ' total.' },
    { k: 'Pauses cut', v: String(cuts.length), note: cuts.length ? MODE_NOTE[mode](minSilence, mode === 'shorten' ? maxSilence : pad) : (mode === 'trim' ? 'No silence at the very start or end of this file.' : 'No pause in this file is longer than ' + minSilence + 's.') },
    { k: 'Removed', v: out.removed.toFixed(2) + 's <small>(' + removedPct.toFixed(0) + '%)</small>' },
    { k: 'New length', v: fmtTime(newDuration) },
  ]

  const viz = makeViz(speech, cuts, duration)
  return { audio: { channelData: out.data, sampleRate: fs }, report, ...(viz ? { viz } : {}), suffix: '-desilenced' }
}
