// Generated by scripts/util-pages.mjs — runs in a module Worker (see util/worker.js)
import { fmtTime } from '/util/util.js'
const load = u => import(u).catch(() => new Promise(r => setTimeout(r, 300)).then(() => import(u)))
export default async function process(a) { return { audio: a } }
